version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Sicheres Passwort verwenden!
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  sudoku:
    build:
      context: ./Sudoku
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    # Stelle sicher, dass deine Anwendung auf Port 8080 läuft

  frontend:
    build:
      context: ./sudoku-frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://sudoku:8080  # ✅ Kommuniziert über den Container-Namen
    depends_on:
      - sudoku
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  db-data: