version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Port als Liste
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Port als Liste
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  # Port als Liste
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sudoku
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

